/**
 * D&D Beyond's closed compendiums, as slug → id and slug → name.
 * **Generated — do not edit.**
 *
 *   npm run harvest:references
 *
 * Committed on purpose: these ids barely change, and having them here means a
 * fresh clone resolves a condition or a glossary term with no network at all,
 * and a cold hover costs one request instead of two. A miss just falls through
 * to the live slug lookup, so a stale table degrades rather than breaks.
 *
 * The names are what makes these compendiums *pickable* — a slug is a URL
 * fragment, and "sleight-of-hand" is not what an author wants to read in a
 * menu. Keyed only by the canonical slug, so the alias keys in `REFERENCE_IDS`
 * (which exist so a macro written either way resolves) don't become duplicate
 * rows. `reference-catalog.ts` title-cases the slug where a name is missing,
 * so the picker works on a clone that hasn't re-run the harvest.
 */
import type { DdbPath } from "./ddb-reference-map.js";

export const REFERENCE_IDS: Partial<Record<DdbPath, Readonly<Record<string, number>>>> = {
  "conditions": {
    "blinded": 1,
    "charmed": 2,
    "deafened": 3,
    "exhaustion": 4,
    "frightened": 5,
    "grappled": 6,
    "incapacitated": 7,
    "invisible": 8,
    "paralyzed": 9,
    "petrified": 10,
    "poisoned": 11,
    "prone": 12,
    "restrained": 13,
    "stunned": 14,
    "unconscious": 15,
  },
  "skills": {
    "acrobatics": 3,
    "animal-handling": 11,
    "arcana": 6,
    "athletics": 2,
    "charisma-deception": 16,
    "charisma-intimidation": 17,
    "charisma-performance": 18,
    "charisma-persuasion": 19,
    "deception": 16,
    "dexterity-acrobatics": 3,
    "dexterity-sleight-of-hand": 4,
    "dexterity-stealth": 5,
    "history": 7,
    "insight": 12,
    "intelligence-arcana": 6,
    "intelligence-history": 7,
    "intelligence-investigation": 8,
    "intelligence-nature": 9,
    "intelligence-religion": 10,
    "intimidation": 17,
    "investigation": 8,
    "medicine": 13,
    "nature": 9,
    "perception": 14,
    "performance": 18,
    "persuasion": 19,
    "religion": 10,
    "sleight-of-hand": 4,
    "stealth": 5,
    "strength-athletics": 2,
    "survival": 15,
    "wisdom-animal-handling": 11,
    "wisdom-insight": 12,
    "wisdom-medicine": 13,
    "wisdom-perception": 14,
    "wisdom-survival": 15,
  },
  "senses": {
    "blindsight": 1,
    "darkvision": 2,
    "tremorsense": 3,
    "truesight": 4,
    "unknown": 5,
  },
  "actions": {
    "attack": 1,
    "dash": 4,
    "disengage": 5,
    "dodge": 6,
    "help": 7,
    "hide": 8,
    "magic": 2,
    "ready": 9,
    "search": 10,
    "utilize": 11,
  },
  "weapon-properties": {
    "ammunition": 1,
    "ammunition-firearms": 13,
    "burst-fire": 14,
    "cleave": 18,
    "explosive": 17,
    "finesse": 2,
    "graze": 19,
    "heavy": 3,
    "light": 4,
    "loading": 5,
    "misfire": 16,
    "nick": 20,
    "range": 7,
    "reach": 8,
    "reload": 15,
    "special": 9,
    "thrown": 10,
    "two-handed": 11,
    "versatile": 12,
  },
  "rules-glossary": {
    "ability-check": 1,
    "ability-score-and-modifier": 2,
    "action": 3,
    "advantage": 4,
    "adventure": 5,
    "alignment": 6,
    "ally": 7,
    "area-of-effect": 8,
    "armor-class": 9,
    "armor-training": 10,
    "attack-roll": 11,
    "attitude": 12,
    "attunement": 13,
    "bloodied": 14,
    "bonus-action": 15,
    "breaking-objects": 20,
    "bright-light": 21,
    "burning-hazard": 22,
    "burrow-speed": 23,
    "campaign": 24,
    "cantrip": 25,
    "carrying-capacity": 26,
    "challenge-rating": 27,
    "character-sheet": 28,
    "climb-speed": 30,
    "climbing": 29,
    "concentration": 31,
    "condition": 16,
    "cone-area-of-effect": 17,
    "cover": 18,
    "crawling": 34,
    "creature": 35,
    "creature-type": 36,
    "critical-hit": 37,
    "cube-area-of-effect": 38,
    "cursed": 127,
    "curses": 39,
    "cylinder-area-of-effect": 40,
    "d20-test": 41,
    "damage": 42,
    "damage-roll": 43,
    "damage-threshold": 44,
    "damage-types": 45,
    "darkness": 46,
    "dead": 47,
    "death-saving-throw": 48,
    "dehydration-hazard": 49,
    "difficult-terrain": 50,
    "difficulty-class": 51,
    "dim-light": 52,
    "disadvantage": 53,
    "emanation-area-of-effect": 54,
    "encounter": 55,
    "enemy": 56,
    "experience-points": 57,
    "expertise": 58,
    "falling-hazard": 59,
    "fly-speed": 61,
    "flying": 60,
    "friendly-attitude": 62,
    "half-cover": 19,
    "hazard": 63,
    "healing": 64,
    "heavily-obscured": 65,
    "heroic-inspiration": 66,
    "high-jump": 67,
    "hit-point-dice": 68,
    "hit-points": 69,
    "hostile-attitude": 70,
    "hover": 71,
    "illusions": 72,
    "immunity": 73,
    "improvised-weapons": 74,
    "indifferent-attitude": 75,
    "initiative": 76,
    "jumping": 77,
    "knocking-out-a-creature": 78,
    "lightly-obscured": 79,
    "line-area-of-effect": 80,
    "long-jump": 81,
    "long-rest": 82,
    "magical-effect": 83,
    "malnutrition-hazard": 84,
    "monster": 85,
    "nonplayer-character": 86,
    "object": 87,
    "occupied-space": 88,
    "passive-perception": 89,
    "per-day": 90,
    "player-character": 91,
    "possession": 92,
    "proficiency": 93,
    "reach": 126,
    "reaction": 94,
    "resistance": 95,
    "ritual": 96,
    "round-down": 97,
    "save": 98,
    "saving-throw": 99,
    "shape-shift": 125,
    "shape-shifting": 100,
    "short-rest": 101,
    "simultaneous-effects": 102,
    "size": 103,
    "skill": 104,
    "speed": 105,
    "spell": 106,
    "spell-attack": 107,
    "spellcasting-focus": 108,
    "sphere-area-of-effect": 109,
    "stable": 110,
    "stat-block": 111,
    "suffocation-hazard": 112,
    "surprise": 113,
    "swim-speed": 115,
    "swimming": 114,
    "target": 116,
    "telepathy": 117,
    "teleportation": 118,
    "temporary-hit-points": 119,
    "three-quarters-cover": 32,
    "total-cover": 33,
    "unarmed-strike": 120,
    "unoccupied-space": 121,
    "vulnerability": 122,
    "weapon": 123,
    "weapon-attack": 124,
  },
};

export const REFERENCE_NAMES: Partial<Record<DdbPath, Readonly<Record<string, string>>>> = {
  "conditions": {
    "blinded": "Blinded",
    "charmed": "Charmed",
    "deafened": "Deafened",
    "exhaustion": "Exhaustion",
    "frightened": "Frightened",
    "grappled": "Grappled",
    "incapacitated": "Incapacitated",
    "invisible": "Invisible",
    "paralyzed": "Paralyzed",
    "petrified": "Petrified",
    "poisoned": "Poisoned",
    "prone": "Prone",
    "restrained": "Restrained",
    "stunned": "Stunned",
    "unconscious": "Unconscious",
  },
  "skills": {
    "acrobatics": "Dexterity (Acrobatics)",
    "animal-handling": "Wisdom (Animal Handling)",
    "arcana": "Intelligence (Arcana)",
    "athletics": "Strength (Athletics)",
    "deception": "Charisma (Deception)",
    "history": "Intelligence (History)",
    "insight": "Wisdom (Insight)",
    "intimidation": "Charisma (Intimidation)",
    "investigation": "Intelligence (Investigation)",
    "medicine": "Wisdom (Medicine)",
    "nature": "Intelligence (Nature)",
    "perception": "Wisdom (Perception)",
    "performance": "Charisma (Performance)",
    "persuasion": "Charisma (Persuasion)",
    "religion": "Intelligence (Religion)",
    "sleight-of-hand": "Dexterity (Sleight of Hand)",
    "stealth": "Dexterity (Stealth)",
    "survival": "Wisdom (Survival)",
  },
  "senses": {
    "blindsight": "Blindsight",
    "darkvision": "Darkvision",
    "tremorsense": "Tremorsense",
    "truesight": "Truesight",
    "unknown": "Unknown",
  },
  "actions": {
    "attack": "Attack",
    "dash": "Dash",
    "disengage": "Disengage",
    "dodge": "Dodge",
    "help": "Help",
    "hide": "Hide",
    "magic": "Magic",
    "ready": "Ready",
    "search": "Search",
    "utilize": "Utilize",
  },
  "weapon-properties": {
    "ammunition": "Ammunition",
    "ammunition-firearms": "Ammunition (Firearms)",
    "burst-fire": "Burst Fire",
    "cleave": "Cleave",
    "explosive": "Explosive",
    "finesse": "Finesse",
    "graze": "Graze",
    "heavy": "Heavy",
    "light": "Light",
    "loading": "Loading",
    "misfire": "Misfire",
    "nick": "Nick",
    "range": "Range",
    "reach": "Reach",
    "reload": "Reload",
    "special": "Special",
    "thrown": "Thrown",
    "two-handed": "Two-Handed",
    "versatile": "Versatile",
  },
  "rules-glossary": {
    "ability-check": "Ability Check",
    "ability-score-and-modifier": "Ability Score and Modifier",
    "action": "Action",
    "advantage": "Advantage",
    "adventure": "Adventure",
    "alignment": "Alignment",
    "ally": "Ally",
    "area-of-effect": "Area of Effect",
    "armor-class": "Armor Class",
    "armor-training": "Armor Training",
    "attack-roll": "Attack Roll",
    "attitude": "Attitude",
    "attunement": "Attunement",
    "bloodied": "Bloodied",
    "bonus-action": "Bonus Action",
    "breaking-objects": "Breaking Objects",
    "bright-light": "Bright Light",
    "burning-hazard": "Burning [Hazard]",
    "burrow-speed": "Burrow Speed",
    "campaign": "Campaign",
    "cantrip": "Cantrip",
    "carrying-capacity": "Carrying Capacity",
    "challenge-rating": "Challenge Rating",
    "character-sheet": "Character Sheet",
    "climb-speed": "Climb Speed",
    "climbing": "Climbing",
    "concentration": "Concentration",
    "condition": "Condition",
    "cone-area-of-effect": "Cone [Area of Effect]",
    "cover": "Cover",
    "crawling": "Crawling",
    "creature": "Creature",
    "creature-type": "Creature Type",
    "critical-hit": "Critical Hit",
    "cube-area-of-effect": "Cube [Area of Effect]",
    "cursed": "Cursed",
    "curses": "Curses",
    "cylinder-area-of-effect": "Cylinder [Area of Effect]",
    "d20-test": "D20 Test",
    "damage": "Damage",
    "damage-roll": "Damage Roll",
    "damage-threshold": "Damage Threshold",
    "damage-types": "Damage Types",
    "darkness": "Darkness",
    "dead": "Dead",
    "death-saving-throw": "Death Saving Throw",
    "dehydration-hazard": "Dehydration [Hazard]",
    "difficult-terrain": "Difficult Terrain",
    "difficulty-class": "Difficulty Class",
    "dim-light": "Dim Light",
    "disadvantage": "Disadvantage",
    "emanation-area-of-effect": "Emanation [Area of Effect]",
    "encounter": "Encounter",
    "enemy": "Enemy",
    "experience-points": "Experience Points",
    "expertise": "Expertise",
    "falling-hazard": "Falling [Hazard]",
    "fly-speed": "Fly Speed",
    "flying": "Flying",
    "friendly-attitude": "Friendly [Attitude]",
    "half-cover": "Half Cover",
    "hazard": "Hazard",
    "healing": "Healing",
    "heavily-obscured": "Heavily Obscured",
    "heroic-inspiration": "Heroic Inspiration",
    "high-jump": "High Jump",
    "hit-point-dice": "Hit Point Dice",
    "hit-points": "Hit Points",
    "hostile-attitude": "Hostile [Attitude]",
    "hover": "Hover",
    "illusions": "Illusions",
    "immunity": "Immunity",
    "improvised-weapons": "Improvised Weapons",
    "indifferent-attitude": "Indifferent [Attitude]",
    "initiative": "Initiative",
    "jumping": "Jumping",
    "knocking-out-a-creature": "Knocking Out a Creature",
    "lightly-obscured": "Lightly Obscured",
    "line-area-of-effect": "Line [Area of Effect]",
    "long-jump": "Long Jump",
    "long-rest": "Long Rest",
    "magical-effect": "Magical Effect",
    "malnutrition-hazard": "Malnutrition [Hazard]",
    "monster": "Monster",
    "nonplayer-character": "Nonplayer Character",
    "object": "Object",
    "occupied-space": "Occupied Space",
    "passive-perception": "Passive Perception",
    "per-day": "Per Day",
    "player-character": "Player Character",
    "possession": "Possession",
    "proficiency": "Proficiency",
    "reach": "Reach",
    "reaction": "Reaction",
    "resistance": "Resistance",
    "ritual": "Ritual",
    "round-down": "Round Down",
    "save": "Save",
    "saving-throw": "Saving Throw",
    "shape-shift": "Shape-Shift",
    "shape-shifting": "Shape-Shifting",
    "short-rest": "Short Rest",
    "simultaneous-effects": "Simultaneous Effects",
    "size": "Size",
    "skill": "Skill",
    "speed": "Speed",
    "spell": "Spell",
    "spell-attack": "Spell Attack",
    "spellcasting-focus": "Spellcasting Focus",
    "sphere-area-of-effect": "Sphere [Area of Effect]",
    "stable": "Stable",
    "stat-block": "Stat Block",
    "suffocation-hazard": "Suffocation [Hazard]",
    "surprise": "Surprise",
    "swim-speed": "Swim Speed",
    "swimming": "Swimming",
    "target": "Target",
    "telepathy": "Telepathy",
    "teleportation": "Teleportation",
    "temporary-hit-points": "Temporary Hit Points",
    "three-quarters-cover": "Three-Quarters Cover",
    "total-cover": "Total Cover",
    "unarmed-strike": "Unarmed Strike",
    "unoccupied-space": "Unoccupied Space",
    "vulnerability": "Vulnerability",
    "weapon": "Weapon",
    "weapon-attack": "Weapon Attack",
  },
};
